package com.bean;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.no
     *
     * @mbggenerated
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.hp
     *
     * @mbggenerated
     */
    private Integer hp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    public Test(Integer no, String name, Integer hp) {
        this.no = no;
        this.name = name;
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    public Test() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.no
     *
     * @return the value of test.no
     *
     * @mbggenerated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.no
     *
     * @param no the value for test.no
     *
     * @mbggenerated
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.hp
     *
     * @return the value of test.hp
     *
     * @mbggenerated
     */
    public Integer getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.hp
     *
     * @param hp the value for test.hp
     *
     * @mbggenerated
     */
    public void setHp(Integer hp) {
        this.hp = hp;
    }
}